#requires -Version 7.0
[CmdletBinding()]
param(
    [string]$AgentDir,
    [string]$CodexHome,
    [switch]$Compact,
    [AllowEmptyString()][string]$ExternalSkillsRoot,
    [switch]$BackupConflicts
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
if (-not $IsWindows) { throw 'This installer requires native Windows PowerShell 7.' }
$repo = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
if (-not $AgentDir) { $AgentDir = if ($env:PI_CODING_AGENT_DIR) { $env:PI_CODING_AGENT_DIR } else { Join-Path $env:USERPROFILE '.pi/agent' } }
if (-not $CodexHome) { $CodexHome = if ($env:CODEX_HOME) { $env:CODEX_HOME } else { Join-Path $env:USERPROFILE '.codex' } }
$AgentDir = [IO.Path]::GetFullPath($AgentDir)
$resources = Get-Content "$repo/shared/resources.json" -Raw | ConvertFrom-Json
$externalGroups = [ordered]@{}
if ($resources.externalSkillGroups) {
    foreach ($property in $resources.externalSkillGroups.PSObject.Properties) {
        $externalGroups[$property.Name] = $property.Value
    }
}
if ($PSBoundParameters.ContainsKey('ExternalSkillsRoot') -and $ExternalSkillsRoot) {
    if ($externalGroups.Count -gt 0) { throw 'externalSkillGroups already configured; edit shared/resources.json instead of passing -ExternalSkillsRoot.' }
    $ExternalSkillsRoot = [IO.Path]::GetFullPath($ExternalSkillsRoot)
    if (-not (Test-Path -LiteralPath $ExternalSkillsRoot -PathType Container)) { throw "External skills root not found: $ExternalSkillsRoot" }
    $externalGroups['external'] = $ExternalSkillsRoot
}
function Assert-PlainParents([string]$Path) {
    $cursor = [IO.Path]::GetFullPath($Path)
    while ($cursor) {
        $item = Get-Item -LiteralPath $cursor -Force -ErrorAction SilentlyContinue
        if ($item -and (-not $item.PSIsContainer -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint))) { throw "Unsafe destination parent: $cursor" }
        $cursor = Split-Path $cursor -Parent
    }
}
function Hash-Text([string]$Text) {
    return [Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($Text)))
}
$policyPath = Join-Path $CodexHome 'AGENTS.md'
if ($Compact) {
    $policyPath = Join-Path $repo 'pi/harness/AGENTS.md'
    $policy = (Get-Content -LiteralPath $policyPath -Raw).Trim()
    $main = ''
} else {
$policy = Get-Content -LiteralPath $policyPath -Raw
$boundary = $policy.IndexOf($resources.commonPolicyEndHeading, [StringComparison]::Ordinal)
if ($boundary -lt 0) { throw 'Common policy boundary missing; review AGENTS.md before installing.' }
$policy = $policy.Substring(0, $boundary).Trim()
$main = Get-Content "$repo/pi/agents/main.md" -Raw
}
$loopPolicy = Get-Content "$repo/shared/loop-prevention.md" -Raw
$agentsText = "<!-- Generated by codex_setting/scripts/install-pi.ps1; do not edit. -->`n<!-- Common source: $policyPath -->`n$policy`n`n$($main.Trim())`n`n$($loopPolicy.Trim())`n"
$links = [ordered]@{}
if ($Compact) { $links['skills/pi-workflow'] = Join-Path $repo 'pi/harness/skills/pi-workflow' }
foreach ($name in $resources.skills) {
    if ($name -notmatch '^[a-z0-9-]+$') { throw "Invalid skill name: $name" }
    $source = Join-Path $repo "skills/$name"
    if (-not (Test-Path -LiteralPath "$source/SKILL.md" -PathType Leaf)) { throw "Missing skill: $source" }
    $links["skills/$name"] = $source
}
foreach ($groupName in $externalGroups.Keys) {
    if ($groupName -notmatch '^[a-z0-9-]+$') { throw "Invalid external skill group name: $groupName" }
    $configured = [string]$externalGroups[$groupName]
    $groupPath = if ([IO.Path]::IsPathRooted($configured)) { [IO.Path]::GetFullPath($configured) } else { [IO.Path]::GetFullPath((Join-Path $repo $configured)) }
    if (-not (Test-Path -LiteralPath $groupPath -PathType Container)) { throw "External skill group not found: $groupPath" }
    $groupPath = (Get-Item -LiteralPath $groupPath).FullName
    $skillCount = @(Get-ChildItem -LiteralPath $groupPath -Directory | Where-Object { Test-Path -LiteralPath (Join-Path $_.FullName 'SKILL.md') -PathType Leaf }).Count
    if ($skillCount -eq 0) { throw "External skill group has no skills: $groupPath" }
    # Link the grouping directory, preserving all sibling knowledge references.
    $links["skills/$groupName"] = $groupPath
}
$links['agents'] = Join-Path $repo 'pi/agents'
$links['extensions/codex-settings'] = Join-Path $repo 'pi/extensions'
foreach ($target in $links.Values) {
    if (-not (Test-Path -LiteralPath $target -PathType Container)) { throw "Missing source: $target" }
}
Assert-PlainParents $AgentDir
Assert-PlainParents "$AgentDir/codex-settings"
if (Test-Path -LiteralPath "$AgentDir/AGENTS.override.md") { throw 'AGENTS.override.md would shadow the generated policy; reconcile it first.' }
foreach ($relative in $links.Keys) { Assert-PlainParents (Split-Path (Join-Path $AgentDir $relative) -Parent) }
New-Item -ItemType Directory -Path "$AgentDir/codex-settings" -Force | Out-Null
$lockItem = Get-Item -LiteralPath "$AgentDir/codex-settings/install.lock" -Force -ErrorAction SilentlyContinue
if ($lockItem -and ($lockItem.Attributes -band [IO.FileAttributes]::ReparsePoint)) { throw 'Linked installer lock refused' }
$lock = [IO.File]::Open("$AgentDir/codex-settings/install.lock", 'OpenOrCreate', 'ReadWrite', 'None')
try {
    $statePath = "$AgentDir/codex-settings/pi.json"
    $state = $null
    if (Test-Path -LiteralPath $statePath) {
        if ((Get-Item -LiteralPath $statePath).Attributes -band [IO.FileAttributes]::ReparsePoint) { throw 'Linked state refused' }
        $state = Get-Content -LiteralPath $statePath -Raw | ConvertFrom-Json
        if ($state.schema -ne 'codex-settings.pi.v1') { throw 'Unknown pi installer state' }
    }
    $plan = [Collections.Generic.List[object]]::new()
    foreach ($relative in $links.Keys) {
        $dest = Join-Path $AgentDir $relative
        $existing = Get-Item -LiteralPath $dest -Force -ErrorAction SilentlyContinue
        if ($existing -and $existing.LinkType -eq 'Junction' -and [IO.Path]::GetFullPath($existing.Target) -eq [IO.Path]::GetFullPath($links[$relative])) { continue }
        if ($existing -and -not $BackupConflicts) { throw "Conflict: $dest. Preserve/reconcile it, or explicitly use -BackupConflicts." }
        $plan.Add(@{ Relative = $relative; Dest = $dest; Target = $links[$relative]; Existing = [bool]$existing })
    }
    $agentsPath = "$AgentDir/AGENTS.md"
    $existing = Get-Item -LiteralPath $agentsPath -Force -ErrorAction SilentlyContinue
    $desiredHash = Hash-Text $agentsText
    $actualHash = if ($existing -and -not $existing.PSIsContainer -and -not ($existing.Attributes -band [IO.FileAttributes]::ReparsePoint)) { (Get-FileHash -LiteralPath $agentsPath).Hash } else { '' }
    if ($actualHash -ne $desiredHash) {
        $managed = $state -and $actualHash -and $actualHash -eq $state.agentsHash
        if ($existing -and -not $managed -and -not $BackupConflicts) { throw "Conflict: $agentsPath. Local instructions preserved; use -BackupConflicts only after review." }
        $plan.Add(@{ Relative = 'AGENTS.md'; Dest = $agentsPath; Target = $null; Existing = [bool]$existing })
    }
    # The mutable native settings/auth files are never linked, copied or rewritten.
    $backup = Join-Path $AgentDir ('codex-settings/backup-' + [guid]::NewGuid())
    $applied = [Collections.Generic.List[object]]::new()
    try {
        foreach ($entry in $plan) {
            New-Item -ItemType Directory -Path (Split-Path $entry.Dest -Parent) -Force | Out-Null
            $entry.Backup = $null
            $entry.Created = $false
            $applied.Add($entry)
            if ($entry.Existing) {
                $entry.Backup = Join-Path $backup $entry.Relative
                New-Item -ItemType Directory -Path (Split-Path $entry.Backup -Parent) -Force | Out-Null
                Move-Item -LiteralPath $entry.Dest -Destination $entry.Backup
            }
            if ($entry.Target) { New-Item -ItemType Junction -Path $entry.Dest -Target $entry.Target | Out-Null }
            else { [IO.File]::WriteAllText($entry.Dest, $agentsText, [Text.UTF8Encoding]::new($false)) }
            $entry.Created = $true
        }
        $stateText = @{ schema = 'codex-settings.pi.v1'; agentsHash = $desiredHash; policySource = $policyPath; links = $links } | ConvertTo-Json -Depth 5
        if (-not (Test-Path -LiteralPath $statePath) -or (Get-Content -LiteralPath $statePath -Raw) -cne $stateText) {
            $stage = "$statePath.$([guid]::NewGuid()).tmp"
            [IO.File]::WriteAllText($stage, $stateText)
            [IO.File]::Move($stage, $statePath, $true)
        }
    } catch {
        for ($i = $applied.Count - 1; $i -ge 0; $i--) {
            $entry = $applied[$i]
            if ($entry.Created) {
                # Delete only our new link/file, never recurse into its target.
                if ($entry.Target) { [IO.Directory]::Delete($entry.Dest) }
                else { [IO.File]::Delete($entry.Dest) }
            }
            if ($entry.Backup -and (Test-Path -LiteralPath $entry.Backup)) { Move-Item -LiteralPath $entry.Backup -Destination $entry.Dest }
        }
        throw
    }
    if (Test-Path -LiteralPath $backup) { Write-Output "Backup: $backup" }
    Write-Output "PI_INSTALLED changes=$($plan.Count) agentDir=$AgentDir"
} finally { $lock.Dispose() }
